"""param carte

Revision ID: 1fc3a19ca07e
Revises: 4700399372e0
Create Date: 2025-04-01 09:25:48.582009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc3a19ca07e'
down_revision = '4700399372e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('center_lat', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('center_lng', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('zoom', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartes', schema=None) as batch_op:
        batch_op.drop_column('zoom')
        batch_op.drop_column('center_lng')
        batch_op.drop_column('center_lat')

    # ### end Alembic commands ###
