"""ajout relation user_site_role

Revision ID: 37d055509287
Revises: 1fc3a19ca07e
Create Date: 2025-04-02 11:29:03.477812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d055509287'
down_revision = '1fc3a19ca07e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_site_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'site_id', 'role_id')
    )
    op.drop_table('user_sites')
    op.drop_table('user_roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='FK__user_role__role___08D548FA'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='FK__user_role__user___09C96D33'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='PK__user_rol__6EDEA1534E2EF393')
    )
    op.create_table('user_sites',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name='FK__user_site__site___0CA5D9DE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='FK__user_site__user___0D99FE17'),
    sa.PrimaryKeyConstraint('user_id', 'site_id', name='PK__user_sit__029CCAB36A92EC56')
    )
    op.drop_table('user_site_role')
    # ### end Alembic commands ###
